### ISSUE TITLE
Pas à jour

### ISSUE THREAD

**Issue by enzofrnt** [BideoGemu/RagnaModVIIOnDocker#1]
Salut, il semble que les mods ne soient plus à jour.

**Comment by BideoGemu** [comment]
Effectivement on est sur une ancienne version du modpack, suite à pas mal de soucis avec mon PC j'ai pas pu m'occuper de la mise à jour. Je fais cela dès que mon PC est de nouveau fonctionnel à 100%.

**Comment by BideoGemu** [comment]
Je viens de vérifier et je ne fourni aucun mod ni rien le modpack est à télécharger directement sur curseforge. C'est uniquement le container docker pré-configuré, il n'y a donc aucun souci de mise à jour de mods puisque la seule chose qui pourrait avoir changer c'est la version de forge qui est passée en 40.2.17. je met donc à jour avec la bonne version de forge mais si il y a un souci de mod pas à jour c'est sur le download du pack qu'il faut regarder quelle est la version qui a été prise sur curseforge.
