### ISSUE TITLE
Server Image Out Of Date - Mods Missing

### ISSUE THREAD

**Issue by ProRedCat** [BideoGemu/RagnaModVIIOnDocker#2]
Tried running the server image and it does not appear to pull down any mods as the mods folder is empty

This could be similar to #1, would it be possible to update the image?

![image](https://github.com/BideoGemu/RagnaModVIIOnDocker/assets/43058406/22ed132a-8243-4c2b-b70b-5fb9e28fbe47)

**Comment by BideoGemu** [comment]
As shown in the readme : ```Download RagnaMod VII server files on curse forge and put in minecraft directory (with this docker-compose file, in directory: ./files) files and directory```

It is therefore normal that the mods folder is empty, curseforge prohibits the downloading of mods on third-party platforms such as github, so you must manually download the server pack to add it to the server.
